#!/usr/bin/env python3

import subprocess
from getpass import getuser
from pathlib import Path

def s(c):
    return subprocess.run(
        c.split(),
        capture_output = True, text = True,
        check = True
    ).stdout.strip()

assert getuser() == 'root'

s('dmsetup remove windows')

s(f'losetup -d {Path("/tmp/loop_gpt").readlink()}')
Path('/tmp/loop_gpt').unlink()
